movement_speed: 300
bomb_movement_speed: 600
max_movement_speed: 100
item_movement_speed_decrease: 50
bomb_count: 1
bomb_timeout: 3000
explosion_duration: 1000
explosion_spread: 2
back_up_interval: 3
room_expiration_seconds: 300 # 5 min (without action in room)
max_rooms_per_player: 3
